export const noteNames = [
  'C',
  'C#',
  'D',
  'D#',
  'E',
  'F',
  'F#',
  'G',
  'G#',
  'A',
  'A#',
  'B',
] as const;
export type NoteName = (typeof noteNames)[number];

export const noteIntervals = [
  'unison',
  'minor2nd',
  'major2nd',
  'minor3rd',
  'major3rd',
  'perfect4th',
  'diminished5th',
  'perfect5th',
  'minor6th',
  'major6th',
  'minor7th',
  'major7th',
] as const;
export type NoteInterval = (typeof noteIntervals)[number];

export type IntervalNotes = { [key in NoteInterval]: NoteName };

export const notes: IntervalNotes[] = [
  {
    unison: 'C',
    minor2nd: 'C#',
    major2nd: 'D',
    minor3rd: 'D#',
    major3rd: 'E',
    perfect4th: 'F',
    diminished5th: 'F#',
    perfect5th: 'G',
    minor6th: 'G#',
    major6th: 'A',
    minor7th: 'A#',
    major7th: 'B',
  },
  {
    unison: 'C#',
    minor2nd: 'D',
    major2nd: 'D#',
    minor3rd: 'E',
    major3rd: 'F',
    perfect4th: 'F#',
    diminished5th: 'G',
    perfect5th: 'G#',
    minor6th: 'A',
    major6th: 'A#',
    minor7th: 'B',
    major7th: 'C',
  },
  {
    unison: 'D',
    minor2nd: 'D#',
    major2nd: 'E',
    minor3rd: 'F',
    major3rd: 'F#',
    perfect4th: 'G',
    diminished5th: 'G#',
    perfect5th: 'A',
    minor6th: 'A#',
    major6th: 'B',
    minor7th: 'C',
    major7th: 'C#',
  },
  {
    unison: 'D#',
    minor2nd: 'E',
    major2nd: 'F',
    minor3rd: 'F#',
    major3rd: 'G',
    perfect4th: 'G#',
    diminished5th: 'A',
    perfect5th: 'A#',
    minor6th: 'B',
    major6th: 'C',
    minor7th: 'C#',
    major7th: 'D',
  },
  {
    unison: 'E',
    minor2nd: 'F',
    major2nd: 'F#',
    minor3rd: 'G',
    major3rd: 'G#',
    perfect4th: 'A',
    diminished5th: 'A#',
    perfect5th: 'B',
    minor6th: 'C',
    major6th: 'C#',
    minor7th: 'D',
    major7th: 'D#',
  },
  {
    unison: 'F',
    minor2nd: 'F#',
    major2nd: 'G',
    minor3rd: 'G#',
    major3rd: 'A',
    perfect4th: 'A#',
    diminished5th: 'B',
    perfect5th: 'C',
    minor6th: 'C#',
    major6th: 'D',
    minor7th: 'D#',
    major7th: 'E',
  },
  {
    unison: 'F#',
    minor2nd: 'G',
    major2nd: 'G#',
    minor3rd: 'A',
    major3rd: 'A#',
    perfect4th: 'B',
    diminished5th: 'C',
    perfect5th: 'C#',
    minor6th: 'D',
    major6th: 'D#',
    minor7th: 'E',
    major7th: 'F',
  },
  {
    unison: 'G',
    minor2nd: 'G#',
    major2nd: 'A',
    minor3rd: 'A#',
    major3rd: 'B',
    perfect4th: 'C',
    diminished5th: 'C#',
    perfect5th: 'D',
    minor6th: 'D#',
    major6th: 'E',
    minor7th: 'F',
    major7th: 'F#',
  },
  {
    unison: 'G#',
    minor2nd: 'A',
    major2nd: 'A#',
    minor3rd: 'B',
    major3rd: 'C',
    perfect4th: 'C#',
    diminished5th: 'D',
    perfect5th: 'D#',
    minor6th: 'E',
    major6th: 'F',
    minor7th: 'F#',
    major7th: 'G',
  },
  {
    unison: 'A',
    minor2nd: 'A#',
    major2nd: 'B',
    minor3rd: 'C',
    major3rd: 'C#',
    perfect4th: 'D',
    diminished5th: 'D#',
    perfect5th: 'E',
    minor6th: 'F',
    major6th: 'F#',
    minor7th: 'G',
    major7th: 'G#',
  },
  {
    unison: 'A#',
    minor2nd: 'B',
    major2nd: 'C',
    minor3rd: 'C#',
    major3rd: 'D',
    perfect4th: 'D#',
    diminished5th: 'E',
    perfect5th: 'F',
    minor6th: 'F#',
    major6th: 'G',
    minor7th: 'G#',
    major7th: 'A',
  },
  {
    unison: 'B',
    minor2nd: 'C',
    major2nd: 'C#',
    minor3rd: 'D',
    major3rd: 'D#',
    perfect4th: 'E',
    diminished5th: 'F',
    perfect5th: 'F#',
    minor6th: 'G',
    major6th: 'G#',
    minor7th: 'A',
    major7th: 'A#',
  },
];

export const intervalShortNames = {
  unison: 'U',
  minor2nd: 'm2',
  major2nd: 'M2',
  minor3rd: 'm3',
  major3rd: 'M3',
  perfect4th: 'P4',
  augmented4th: 'A4',
  diminished5th: 'd5',
  perfect5th: 'P5',
  minor6th: 'm6',
  major6th: 'M6',
  minor7th: 'm7',
  major7th: 'M7',
};

export const scaleIntervals = {
  major: [
    'unison',
    'major2nd',
    'major3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'major7th',
  ],
  minor: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'minor7th',
  ],
  harmonicMinor: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'major7th',
  ],
  melodicMinor: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'major7th',
  ],
  majorPentatonic: ['unison', 'major2nd', 'major3rd', 'perfect5th', 'major6th'],
  minorPentatonic: [
    'unison',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor7th',
  ],
  blues: [
    'unison',
    'minor3rd',
    'perfect4th',
    'diminished5th',
    'perfect5th',
    'minor7th',
  ],
  diminished: [
    'unison',
    'minor2nd',
    'minor3rd',
    'major3rd',
    'perfect4th',
    'diminished5th',
    'minor6th',
    'major6th',
    'minor7th',
  ],
  wholeTone: [
    'unison',
    'major2nd',
    'major3rd',
    'diminished5th',
    'minor6th',
    'minor7th',
  ],
  chromatic: [
    'unison',
    'minor2nd',
    'major2nd',
    'minor3rd',
    'major3rd',
    'perfect4th',
    'diminished5th',
    'perfect5th',
    'minor6th',
    'major6th',
    'minor7th',
    'major7th',
  ],
  wholeHalf: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'diminished5th',
    'minor6th',
    'major6th',
    'minor7th',
    'major7th',
  ],
  bebop: [
    'unison',
    'major2nd',
    'major3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'minor7th',
    'major7th',
  ],
  ionian: [
    'unison',
    'major2nd',
    'major3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'major7th',
  ],
  dorian: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'minor7th',
  ],
  phrygian: [
    'unison',
    'minor2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'minor7th',
  ],
  lydian: [
    'unison',
    'major2nd',
    'major3rd',
    'augmented4th',
    'perfect5th',
    'major6th',
    'major7th',
  ],
  mixolydian: [
    'unison',
    'major2nd',
    'major3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'minor7th',
  ],
  aeolian: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'minor7th',
  ],
  locrian: [
    'unison',
    'minor2nd',
    'minor3rd',
    'perfect4th',
    'diminished5th',
    'minor6th',
    'minor7th',
  ],
  hungarianMinor: [
    'unison',
    'major2nd',
    'minor3rd',
    'augmented4th',
    'perfect5th',
    'minor6th',
    'major7th',
  ],
  neapolitanMajor: [
    'unison',
    'minor2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'major6th',
    'major7th',
  ],
  neapolitanMinor: [
    'unison',
    'minor2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'major7th',
  ],
  enigmatic: [
    'unison',
    'minor2nd',
    'major3rd',
    'augmented4th',
    'augmented5th',
    'major6th',
    'major7th',
  ],
  doubleHarmonic: [
    'unison',
    'minor2nd',
    'major3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'major7th',
  ],
  persian: [
    'unison',
    'minor2nd',
    'major3rd',
    'perfect4th',
    'diminished5th',
    'minor6th',
    'major7th',
  ],
  arabian: [
    'unison',
    'major2nd',
    'minor3rd',
    'perfect4th',
    'perfect5th',
    'minor6th',
    'major7th',
  ],
};
